Appointment queries
kstensberg/bizeebird pull request #48
Opened 2022-08-30 20:03 UTC by shawnorrific

2022-08-30 20:30 UTC, kstensberg requested changes

2022-08-30 20:30 UTC, kstensberg commented on db-management/Appointments/queries/getUpcomingDropoffs.js
> +const getUpcomingDropoffs = () => {
see https://github.com/kstensberg/bizeebird-old/blob/master/bizeebird/Ui/MainWindow.cs#L94-#L127 for reference. 

the current implementation includes all the appointment birds in a twirl that's collapsed by default

2022-08-30 20:30 UTC, kstensberg commented on db-management/Appointments/queries/getUpcomingDropoffs.js
> +            'WHERE Appointments.StartTime > date("now", "-30 days") AND Appointments.Status = 1 ' +
current implementation does not filter by 30 days.  

where a.StartTime >= DateTime.Today &&
a.Status == AppointmentStatus.Scheduled

2022-08-30 20:30 UTC, kstensberg commented on db-management/Appointments/queries/getUpcomingPickups.js
> +            'WHERE Appointments.EndTime > date("now", "-30 days") AND Appointments.Status = 2 ' +
current implementation does not filter by 30 days.  filter in current implementation

where a.EndTime >= DateTime.Today && 
                                   a.Status == AppointmentStatus.CheckedIn
                                   orderby a.EndTime ascending

2022-08-30 20:30 UTC, kstensberg commented on db-management/Appointments/queries/getUpcomingPickups.js
> +const getUpcomingDropoffs = () => {
see https://github.com/kstensberg/bizeebird-old/blob/master/bizeebird/Ui/MainWindow.cs#L151-#L185 for reference

the current implementation includes all the appointment birds in a twirl that's collapsed by default

2022-08-30 20:30 UTC, kstensberg commented on ipc.js
> +ipcMain.handle('getUpcomingDropoffs', require('./db-management/Appointments/queries/getUpcomingDropoffs'));
doesn't this now need to pass in a database connection?

2022-08-31 00:50 UTC, shawnorrific commented on ipc.js
> +ipcMain.handle('getUpcomingDropoffs', require('./db-management/Appointments/queries/getUpcomingDropoffs'));
I ended up undoing that work because I couldn't get it working on tests. Let's work on this tomorrow.

2022-09-02 23:06 UTC, merged