added function for deleting a customer
kstensberg/bizeebird pull request #8
Opened 2022-08-17 03:59 UTC by shawnorrific

2022-08-17 06:28 UTC, kstensberg requested changes

2022-08-17 06:28 UTC, kstensberg commented on queries/customerQueries.js
> +const db = new sqlite3.Database('./bizeebird-test.db');
we have this hardcoded somewhere else too.  can we add this to a file we require()?

2022-08-17 06:28 UTC, kstensberg commented on queries/customerQueries.js
> +    return new Promise((resolve, reject) => {
instead of promises, you might want to check out async/await

https://blog.pagesd.info/2019/10/29/use-sqlite-node-async-await/

2022-08-17 06:28 UTC, kstensberg commented on queries/customerQueries.js
> +const customerResult = getSingleCustomer(1);
either this test code should be in a test somewhere or not included

2022-08-17 18:32 UTC, shawnorrific commented on queries/customerQueries.js
> +    return new Promise((resolve, reject) => {
I will look into this later

2022-08-17 18:33 UTC, shawnorrific commented on queries/customerQueries.js
> +const db = new sqlite3.Database('./bizeebird-test.db');
completed

2022-08-17 18:33 UTC, shawnorrific commented on queries/customerQueries.js
> +const customerResult = getSingleCustomer(1);
will work on this later

2022-08-18 05:00 UTC, kstensberg approved these changes

2022-08-20 19:02 UTC, merged